### ISSUE TITLE
: not working on Atom version 1.7.4 Mac OS 10.11.4

### ISSUE THREAD

**Issue by yuzhoul1991** [t9md/atom-vim-mode-plus-ex-mode#9] opened 2016-05-25 04:33 UTC
It seems typing : does not do anything now on the Atom and Mac OS version mentioned in the title. Windows seems to be okay. I did disable the official vim mode and ex mode but did not uninstall them as this version of Atom has a bug of not being able to uninstall packages.

**Comment by johanneserber** [comment] 2016-06-28 13:12
+1 nor does it in Atom 1.8.0

this package is no longer maintained?

**Comment by mahmoudhossam** [comment] 2016-08-07 11:18
I have the same problem on Atom 1.9.6, Arch Linux x64.

**Comment by t9md** [comment] 2016-08-07 14:09
Whats your keymap setting? Does keymap resolver report correctly invoke vmp-ex-mode's command?

**Comment by mahmoudhossam** [comment] 2016-08-07 14:23
I put the code in the readme in my `keymap.cson` but I can't find anything in my keybindings when I search for `ex-mode`.

**Comment by mahmoudhossam** [comment] 2016-08-07 15:18
After restarting atom, the shortcut now works.

**Comment by fohrums** [comment] 2016-08-21 03:33
Confirmed. having an _ex-mode_ to work alongside a Vim package just simply
doesn't work with `Atom_1.9.9` + `Windows 10` also.

```
Atom_1.9.9
win10_Home_x64
```

# VIM-PACKAGES INSTALLED
- `vim-mode-plus`
  - The better vim-mode w/ _visual-block_ support already enabled by default.
- `vim-mode-plus-ex-mode`

# PROBLEM
- Supposedly you combine these 2-packages:
  - `vim-mode-plus`
  - `vim-mode-plus-ex-mode`
    - then you'll be able to use the ex-mode command (:), **but this is not
      working**

# WHY EVEN _EX-MODE_?
- save-file `:w`
- quite-file `:q`, `:q!`
  - Yes, I know there's a package to utilize Vim's function to alternatively
    quite the file through a hotkey `ZZ`, but that doesn't work.
  - maybe it's because i'm using `vim-mode-plus` and `vim-mode-zz` probably requires
    Atom's original `vim-mode`

## NOTE
- I don't wanna go back to Atom's very own `vim-mode` as it lacks the function called _visual-block_, which is extremely crucial for me.
  - Don't even think about suggesting to combine `vim-mode` with
    Yet-Another-Mode-Ex package that doesn't work with it, because I've tried all
    there is.
  - `vim-mode` + `ex-mode` - NOT WORKING
  - `vim-mode` + `vim-modeline` - NOT WORKING
- Weird hotkey when having these 2-packages installed
  - `vim-mode-plus`
  - `vim-mode-plus-ex-mode`
    - closing a tab `CTRL+W` no longer works
    - instead, to close a tab you have to `CTRL+W` & `:`, extremely bizarre
      and frustrating.
- A major problem I have with vim packages is the lack of detail that explains the package
  - they seriously need to include what not to include it with (avoid) along with common mistakes other users may struggle with.

**Comment by t9md** [comment] 2016-08-21 04:52
@fohrums This issue is solved already. your issue is completely new one? not sure.

Did you set  keymap in your `keymap.cson`? 
How about excuting `Vim Mode Plus Ex Mode: Open` from command palette.
If you set keymap described in README.md, what keybindig-resolver says against your `:` keystroke.

For windows issue for `ctrl-w` to close pane-item, see [this links](https://github.com/t9md/atom-vim-mode-plus/wiki/TIPS#how-can-i-use-ctrl-w-to-close-pane).

**Comment by fohrums** [comment] 2016-08-21 22:33
@t9md,

> Did you set keymap in your keymap.cson (_just like in README.md_)?

Thanks this did solve the issue and it's best to note that it doesn't act like
vim's own `:` traditionally;... instead, what you get is Atom's flavor through
the use of it's own _searchbar_ as the `ex-mode`. I was confused for a bit and
didn't realize this _new_ search bar WAS indeed the `ex-mode` (_hence, the as-mentioned bolean
config parameter_).

I would suggest letting users know how to navigate to `keymap.cson` to add
these custom key-bindings that are specific to your `vim-mode-plus-ex-mode`
package. That is, because just simply stating _the following_ doesn't let me know what I
need to do exactly:

> @vim-mode-plus-ex-mode_README.md There is no default keymap.

---

So, i've re-created that step for you. All you need to do know is update your README.md to suggest this...

# PRE-REQUISITE (vim-mode-plus-ex-mode)
- Keybindings for `:` doesn't exist yet, so let's define it
  - Settings > Keybindings > click `your keymap file` at the top
    - input these provided keymappings...

```
'atom-text-editor.vim-mode-plus.normal-mode':
  ':': 'vim-mode-plus-ex-mode:open'
  '!': 'vim-mode-plus-ex-mode:toggle-setting'
```

ENJOY!!

---

> For windows issue for ctrl-w (_as it's currently defined as a prefix-key_) to close pane-item, [see how to solve this issue here.](https://github.com/t9md/atom-vim-mode-plus/wiki/TIPS#how-can-i-use-ctrl-w-to-close-pane).

Man,....you don't change what is common & you don't build over existing
structures.....but these decisions made by Atom makes me wonder, pffft. 
I would be a happy camper with `npp` but it's vim plugin `visimulator` has by
default not enabled the keymapping `CTRL-[` to escape current modes and
closing `npp` will remove the save setting to have it enabled in the first
place. Just that lil' effort missing made me switch to Atom COMPLETELY at a _hunned_!

**Comment by bronson** [comment] 2016-10-07 20:59
Sounds like it's working for everyone (including me).  Seems like this can be closed...?

**Comment by t9md** [comment] 2016-10-08 16:13
Thanks @bronson , will close.

**Closed as completed by t9md** 2016-10-08 16:13 UTC
